"""
Static university and college seed data.
"""

UNIVERSITIES_DATA = [
    {
        "slug": "savitribai-phule-pune-university",
        "name": "Savitribai Phule Pune University",
        "location": "Pune",
        "state": "Maharashtra",
        "type": "Government",
        "stream": "General",
        "nirf": "19",
        "logo_url": "/static/images/logo.png",
    },
    {
        "slug": "university-of-mumbai",
        "name": "University of Mumbai",
        "location": "Mumbai",
        "state": "Maharashtra",
        "type": "Government",
        "stream": "General",
        "nirf": "45",
        "logo_url": "/static/images/logo.png",
    },
    {
        "slug": "rtm-nagpur-university",
        "name": "Rashtrasant Tukadoji Maharaj Nagpur University",
        "location": "Nagpur",
        "state": "Maharashtra",
        "type": "Government",
        "stream": "General",
        "nirf": "74",
        "logo_url": "/static/images/logo.png",
    },
    {
        "slug": "symbiosis-international",
        "name": "Symbiosis International (Deemed University)",
        "location": "Pune",
        "state": "Maharashtra",
        "type": "Deemed",
        "stream": "Management",
        "nirf": "17",
        "logo_url": "/static/images/logo.png",
    },
    {
        "slug": "mit-wpu",
        "name": "MIT World Peace University",
        "location": "Pune",
        "state": "Maharashtra",
        "type": "Private",
        "stream": "Technology",
        "nirf": "96",
        "logo_url": "/static/images/logo.png",
    },
    {
        "slug": "nmims-mumbai",
        "name": "NMIMS University",
        "location": "Mumbai",
        "state": "Maharashtra",
        "type": "Private",
        "stream": "Management",
        "nirf": "49",
        "logo_url": "/static/images/logo.png",
    },
]


COLLEGES_DATA = [
    {
        "name": "COEP Technological University",
        "state": "Maharashtra",
        "city": "Pune",
        "type": "Government",
        "stream": "Engineering",
        "nirf": "73",
        "logo_url": "/static/images/logo.png",
        "source_url": "https://www.coep.org.in",
    },
    {
        "name": "VJTI Mumbai",
        "state": "Maharashtra",
        "city": "Mumbai",
        "type": "Government",
        "stream": "Engineering",
        "nirf": "101-150",
        "logo_url": "/static/images/logo.png",
        "source_url": "https://vjti.ac.in",
    },
    {
        "name": "Fergusson College",
        "state": "Maharashtra",
        "city": "Pune",
        "type": "Autonomous",
        "stream": "Arts & Science",
        "nirf": "58",
        "logo_url": "/static/images/logo.png",
        "source_url": "https://fergusson.edu",
    },
    {
        "name": "St. Xavier's College",
        "state": "Maharashtra",
        "city": "Mumbai",
        "type": "Private",
        "stream": "Arts & Science",
        "nirf": "89",
        "logo_url": "/static/images/logo.png",
        "source_url": "https://xaviers.edu",
    },
    {
        "name": "KJ Somaiya College of Engineering",
        "state": "Maharashtra",
        "city": "Mumbai",
        "type": "Private",
        "stream": "Engineering",
        "nirf": "151-200",
        "logo_url": "/static/images/logo.png",
        "source_url": "https://kjsit.somaiya.edu",
    },
    {
        "name": "Ness Wadia College",
        "state": "Maharashtra",
        "city": "Pune",
        "type": "Aided",
        "stream": "Commerce",
        "nirf": "101-150",
        "logo_url": "/static/images/logo.png",
        "source_url": "https://nesswadia.edu",
    },
]
